
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  workflow_run:
  # Triggers the workflow on push or pull request events but only for the main branch
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    
  deployDev:
    environment: developer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
    # Name of the heroku application to which the build is to be sent.
         heroku_app_name: ${{secrets.HEROKU_APP_NAME}}

    # The email address associated with your Heroku account.
         email: ${{secrets.HEROKU_EMAIL}} 
    # Heroku API key associated with provided user's email.
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}

        
